name: mydepot
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.1
  - ipykernel==5.1.4
  - numpy==1.18.1
  - pandas==1.0.1
  - matplotlib==3.1.3
  - pip==20.0.2
  - pip:
    - -r requirements.txt
    - --editable .
